name: golangci-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ""
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # tag=v6.0.3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # tag=v9.2.1
        with:
          version: v2.11.4
          working-directory: ${{matrix.working-directory}}
